version: '3.9'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: node:20
    restart: unless-stopped
    working_dir: /usr/src/app
    env_file: .env
    volumes:
      - ./web:/usr/src/app
      - ./output:/usr/src/app/output
    command: sh -c "npm install && node server.js"
    depends_on:
      - db
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: db
    ports:
          - "4000:4000"
  cron:
    build:
      context: ./cron
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./cron:/app
      - ./output:/app/output
volumes:
  db_data:
